### ISSUE TITLE
question: how will this be different from your old version?

### ISSUE THREAD

**Issue by Lennium** [MoonchildProductions/Tycho#75]
Pale Moon based on the engine revision 24 had the issue that it was impossible to keep it up-to-date with several new web-standards, for example no promise support, because it got too hard to add new stuff to the code base as you wrote on the board if i remember correctly.

As you said that this is the last porting to a new Gecko engine, as the later ones are removing XUL and get that horrible Google technology called webextensions which makes future engine revisions not compatible with your goals.

If i take a look to that links here

http://kangax.github.io/compat-table/es2016plus/ and http://kangax.github.io/compat-table/esnext

it is visible again that the engine you have chosen is quite a bit behind already, how is that different from your last approach then? How can you be so confident that you will not run into heavy compatibility issues with the web when the community had either not the ability or the interest to support you with code submissions during the old Pale Moon code base? (I hardly do not believe that this will change now)

Wouldn't it have been a much better and more future proof solution to rebuild Pale Moon instead with QT and the new QTWebengine? So you only would be forced to focus on the UI creation, as the engine work is done actually by the QT team?

Just curious, this post is not to offend anyone.

Thanks!

**Comment by wolfbeast** [comment]
The ES features that our current release versions are missing are **landmark** features that have seen relatively **broad adoption**. It's a matter of not only technical availability, it's also a matter of practical use.

ES2016plus, ES version next, etc. is all well and good but if you realize that over 80% of websites out there don't even use features that have been available for over a decade, the ridiculous "everything must do everything" attitude quickly sees rapid decline in adoption. 

How can I be so confident? By being well aware what is actually in use and what is actually needed (and moreover what is actually **not** needed) for even advanced web applications in terms of scripting. Pushing for 100% adoption of the latest ES spec is nonsense. There's a reason why ES6 adoption is not complete in *any* browser. Does that mean we can work with any web application out there that people can think up and justify because their use of features in the language spec? No. Does that mean we're in any way being irrelevant? No, even more so because of the existence of perfectly-valid server-side solutions. What matters is the fact that our web compatibility covers a significant majority of sites out there. There will always be sites that will only render proper in one particular browser because people have moved away from standardization again and worse, specs have become more "describing specific behavior" than actually describing logical standards (see ES6 appendices, for example).
This also isn't something decided overnight. It's been a decision based on a few months of evaluation of available options.

Also, ECMAScript isn't necessarily a set-in-stone standard; it has never been. It's a language specification, of which implementations can wildly differ.

If it wasn't for the Mozilla code base having severe issues with the way promises are implemented (it's in the DOM, not in the JS engine, because self-hosting promises is not possible in Spidermonkey (not even in the latest version) then our current release versions would do just fine with continued improvements.

Also, you seem to think that we're going to freeze the code base at a certain level? If you pay attention, we've already made ES6 additions to Pale Moon that weren't present previously. This re-base overcomes some hurdles that our current development community does not have the capacity to overcome itself. We will still need community help in the future; this isn't a "fix-all", but an important step forward creating a base to continue developing from.

**Comment by wolfbeast** [comment]
Let me add this:

I can't predict the future. I don't claim I can, either. But going by all information available to me this is the right approach and right direction, and gives us a solid base to work from. If you think you can do it better, then please, be my guest! I will fully support whatever other Mozilla fork pops up -- so far as I know we are the only one who have done this until now.

If there simply isn't enough community support for a community-based browser and we end up falling short in a few years time as a result of massive changes in webdesign and broad adoption of those changes requiring a client that we cannot reasonably continue developing with our team of volunteers to this open source project, then it will likely spell the end of Pale Moon as we know it now.
