### ISSUE TITLE
Places "tags" -> uncaught exception

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Tycho#76]
Selecting "tags" in the library window throws an uncaught exception.
````
Error: uncaught exception: 2147942487
````

**Comment by mattatobin** [comment]
According to some Bugzilla Bugs.. this is actually NS_ERROR_ILLEGAL_VALUE: Invalid arguments but thrown from XPCOM it /seems/. It might be caused by not sending the right number of arguments or an argument not being the right datatype.. Least that is what looking through some of these bugs that throw this seem to indicate...

**Comment by wsdfhjxc** [comment]
This not only applies to _Tags_ item but also _History_ item and its sub-items (_Today_), sub-items of _Bookmarks Toolbar_ item (_Most visited_) and sub-items of _Bookmarks Menu_ item (_Recently Bookmarked_, _Recent Tags_).
