### ISSUE TITLE
Build fails when using --enable-shared-js

### ISSUE THREAD

**Issue by trav90** [MoonchildProductions/Tycho#9]
Final link failure on CentOS 6 using GCC 4.9.1 and the --enable-shared-js mozconfig option:

```
../../netwerk/base/Unified_cpp_netwerk_base0.o: In function `PACProxyAlert':
/home/trava90/PaleMoon/Tycho/Tycho/netwerk/base/ProxyAutoConfig.cpp:471: undefined reference to `JS::CallArgs::requireAtLeast(JSContext*, char const*, unsigned int)'
../../netwerk/base/Unified_cpp_netwerk_base0.o: In function `PACDnsResolve':
/home/trava90/PaleMoon/Tycho/Tycho/netwerk/base/ProxyAutoConfig.cpp:419: undefined reference to `JS::CallArgs::requireAtLeast(JSContext*, char const*, unsigned int)'
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.1/ld: libxul.so: hidden symbol `_ZN2JS8CallArgs14requireAtLeastEP9JSContextPKcj' isn't defined
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.1/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```
Likely an easy fix, but needs some investigating.

**Comment by wolfbeast** [comment]
This is a cross-platform issue, actually. trying to build the js library shared won't work.
As you said likely an easy fix; this is undoubtedly caused by Mozilla folding js back into xul, then making changes that broke it and not testing the result in a shared js environment. There's more of that going on in later Firefox code bases; only the intended release configuration is ever tested by them.

**Comment by wolfbeast** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1209684
_Bug 1209684 - --enable-shared-js builds are totally broken_
