### ISSUE TITLE
MOZ_NATIVE_JEMALLOC is broken

### ISSUE THREAD

**Issue by jbeich** [MoonchildProductions/Tycho#90]
FreeBSD ships with jemalloc as system allocator (i.e. malloc(3) family). Since 10.0-RELEASE it can replace memory/jemalloc. This makes statistics a bit more accurate and allows `MALLOC_CONF` to control both ~~Firefox~~ Tycho itself and its dependencies (e.g. Gtk libs). Before d0f8fbdb9592 one could add `export MOZ_JEMALLOC3=1` to `.mozconfig` to enable configure checks for `mallctl()` and `nallocx()` but it's no longer possible. `--enable-jemalloc-lib` tries to force `--enable-jemalloc` via `AC_MSG_ERROR()` but in this case we really don't want `MOZ_MEMORY=1` defined.

Note, memory/mozjemalloc has [bitrotten](https://bugzilla.mozilla.org/show_bug.cgi?id=1153683) FreeBSD support and unlikely to work for other Tier3 platforms thus `--enable-jemalloc` cannot be enabled by default.

**Comment by jbeich** [comment]
Also, downstream may [prefer to avoid](https://www.freebsd.org/doc/en/books/porters-handbook/bundled-libs.html) bundled libraries if Tycho is ever packaged.

**Comment by wolfbeast** [comment]
Without using the in-tree jemalloc or MOZ_MEMORY, the browser will use whatever the system malloc() implementation is. Even if that is jemalloc at the system level. So it's not needed to touch this in our tree for BSD because BSD will use jemalloc as a system alloc in that case. Simply don't use --enable-jemalloc in configure.

**Comment by wolfbeast** [comment]
Considering the breakage of the other PR porting non-core OS patches and apparently separate requirements for the allocator here that would directly impact other OSes as well, it seems to me a better approach would be to separate BSD development out to its own branch. That was master can remain clean and unbusted where core work happens for established OSes.

**Comment by jbeich** [comment]
> Without using the in-tree jemalloc or MOZ_MEMORY, the browser will use whatever the system malloc() implementation is. Even if that is jemalloc at the system level. So it's not needed to touch this in our tree for BSD because BSD will use jemalloc as a system alloc in that case. Simply don't use --enable-jemalloc in configure.

The following features are not available if system allocator is generic. However, since FreeBSD has jemalloc in libc it can hook them without building memory/*jemalloc.
- heap-* stats via mallctl(3) in about:memory (a warning otherwise)
- freeing dirty pages on memory pressure via mallctl(3)
- optimized allocation via nallocx(3) in sqlite and AudioCompactor
- MALLOC_CONF=narenas:1,tcache:false tuning
- G_SLICE=always-malloc tuninig

> and apparently separate requirements for the allocator here that would directly impact other OSes as well,

For ~~Firefox~~ Tycho to build with `MOZ_NATIVE_JEMALLOC` not only `.mozconfig` has to contain `export MOZ_JEMALLOC3=1` but OS has to pass `mallctl()` and `nallocx()` configure checks. All those "other OSes" won't see any difference.

Maybe read [original bug](https://bugzilla.mozilla.org/show_bug.cgi?id=788955) if you don't understand how `MOZ_NATIVE_JEMALLOC` works.

**Comment by wolfbeast** [comment]
So BSD is a "special snowflake" OS -- that's fine, as I stated in my other comment, I suggest you make BSD development separate from our main repositories in that case so you can merge universal code updates and have freedom to adjust anything that's needed for BSD OSes then. Build from your own repo and take care of your RelEng to publish BSD variants, and everyone can be happy.  

And I would greatly appreciate it if you don't think that you can do a straight port of 20+ Mozilla bugs to our tree without consequences, ignoring transitions of mozilla to different build environments apparently, and I would appreciate it even more if you would stop with the "~~Firefox~~ Tycho" already which you have done a few times now, because it is showing us an attitude that really has no place in a browser that has been independent for 7 years going now. It _really_ rubs me the wrong way that you go out of your way to do this.
If you are of the opinion that we are Firefox and treat our code base as if it's a rebuild, then I can only suggest you immediately stop contributing to our code, period, and go contribute to Mozilla products instead.

**Comment by jbeich** [comment]
Please, do not try to change the subject. `MOZ_NATIVE_JEMALLOC` changes have nothing to do with backporting Firefox commits.

> And I would greatly appreciate it if you don't think that you can do a straight port of 20+ Mozilla bugs to our tree without consequences,

Sure, that's what Continuous Integration services are for. Why don't you have one? Do you expect every Linux contributor to have a Windows machine? It'd help to not overreact to a single bustage.

> and I would appreciate it even more if you would stop with the "~~Firefox~~ Tycho" already which you have done a few times now, because it is showing us an attitude that really has no place in a browser that has been independent for 7 years going now.

Apologies. It was meant tongue-in-cheek as Firefox is to blame for the bugs Tycho inherited. `MOZ_NATIVE_JEMALLOC` is on of the very few **regressions** specific to Tycho and Palemoon.

> If you are of the opinion that we are Firefox and treat our code base as if it's a rebuild

I treat Tycho as a fork of Firefox 38 as a fork of Mozilla Suite as a fork of Netscape. Also, DragonFly is a fork of FreeBSD 4.8 is a fork of BSD 4.4. This is how software evolves and the same bugs propagate to other products.

Can you define what's "rebuild"? I don't understand having no Windows background.

**Comment by jbeich** [comment]
Abandoned. I don't have time to maintain a fork.

**Comment by wolfbeast** [comment]
And I don't have time to pick up the pieces from untested ports.
